modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
issueTrackerURL = ""
logoFile = "pack.png"
[[mods]]
modId = "finalevolution"
version = "${file.jarVersion}"
displayName = "Final Evolution"
displayURL = ""
authors = "dk_headcrab_dk"
description = '''
Final Evolution
'''
[[dependencies.finalevolution]]
modId = "forge"
mandatory = true
versionRange = "[40.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.finalevolution]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"